version: 2.1

executors:
  node:
    parameters:
      tag:
        type: string
        default: '10'
    docker:
      - image: circleci/node:<< parameters.tag >>


jobs:
  NodeJS 12:
    executor: { name: node, tag: '12' }
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - ./**

  Dry publish:
    executor: node
    steps:
      - run: echo "Echo, yup."

  Real publish if necessary:
    executor: node
    steps:
      - run: echo "Echo, real publish."

workflows:
  Build and Test:
    jobs:
      - NodeJS 12:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - Dry publish:
          requires:
            - NodeJS 12
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - Real publish if necessary:
          requires:
            - Dry publish
          filters:
            tags:
              only: /^group-/
